### ISSUE TITLE
New columns in soil database

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/SISLAC#12]
We should add three new columns:
Order: text, 25 chars
Hz.design: text, 10 chars <- This one is already there!
Point type: categorical: "soil profile", "auger"

**Comment by midraed** [comment]
We should also add:
Produced by, 25 chars.
Uploaded by: fill with the user who upload the data.

**Comment by mauriciopasquier** [comment]
- `Uploaded by` could be the same field `user` we already have, which is filled with the current system user when creating any profile.
- `Produced by` sounds similar to `Reconocedores` from SiSINTA

**Comment by midraed** [comment]
yeah, its the same as Reconocedores. And oc we can use the user field

**Comment by mauriciopasquier** [comment]
We're still missing `Order` but I'll close this issue in favor of the more specific #15
