### ISSUE TITLE
Data licensing

### ISSUE THREAD

**Issue by mauriciopasquier** [FAO-GSP/SISLAC#14]
@midraed and I discussed how to add licences to each profile data. We will provide the following options on importing and creation of profiles:

- Public Domain Dedication and License (PDDL) — “Public Domain for data/databases”
- Attribution License (ODC-By) — “Attribution for data/databases”
- Open Database License (ODC-ODbL) — “Attribution Share-Alike for data/databases”

ODC-ODbL will be the default choice, ODC-By will be forced upon existing "public" data (maybe this could cause some legal issues?) and we should integrate the license used by WoSIS (CC-BY-NC) but not offer it as a choice on our system.

**Comment by mauriciopasquier** [comment]
On second thought, **ODC-By** is less restrictive (i.e. doesn't enforce share alike) than **ODC-ODbL**, I think I misread our conversation. We should use the more restrictive for existing data.

**Comment by midraed** [comment]
We should include CC licenses even is they are not specifically for data. Because, at least 2 data repositories we want to include, are using it. I mean WoSIS and febr.

**Comment by mauriciopasquier** [comment]
Ok, then I'm adding the two used by WoSIS:

- CC-BY
- CC-BY-NC

Let me know if any other CC license configuration is needed.
