### ISSUE TITLE
About Netherlands Antilles

### ISSUE THREAD

**Issue by mauriciopasquier** [FAO-GSP/SISLAC#3]
In the initial dataset, there are some profiles with country code 'AN', but according to [wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:AN):

> The Netherlands Antilles were officially assigned the ISO 3166-1 alpha-2 code AN before it was dissolved into five separate territories in 2010, and the entry has been deleted from ISO 3166-1 as a result.

So it doesn't exist anymore. It's relevant because when sanitizing the data we are using a standard library.

Currently we are discarding those profiles, is that ok?

**Comment by mauriciopasquier** [comment]
I found this [FAO resource](http://www.fao.org/countryprofiles/geoinfo/geopolitical/resource/Netherlands_Antilles) where `AN` is used.

**Comment by midraed** [comment]
We should keep them. I think we should accept any ISO code, including former ISO code because we want to host legacy data...

**Comment by mauriciopasquier** [comment]
Then we need a "definitive" list of allowed ISOs, because we need to filter every non LAC country on this initial dataset. Yusuf gave me this one:

    ABW AIA ARG ATG BES BHS BLM BLZ BMU BOL BRA BRB CHL COL CRI CUB CUW CYM DMA
    DOM ECU FLK GLP GRD GTM GUF GUY HND HTI JAM KNA LCA MAF MEX MSR MTQ NIC PAN
    PER PRI PRY SGS SLV SUR SXM TCA TTO UMI URY VCT VEN VGB VIR XCL

Which doesn't have the code for `AN` (`ANT`). By the way, it would be better to have the list as alpha2 codes (i.d. 2 letters), because that is what's used in the "source". I can convert the codes and add `AN` to the list but I want to get an official list if there is one.
