### ISSUE TITLE
visibility of soil data on the map

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/SISLAC#9]
Current value of color and transparency makes point bearely visible on the map. Can we change to no transparency and a different colo (yellow?)

**Comment by mauriciopasquier** [comment]
We need a color for public profiles and another for private ones. I used blue (public) and orange (private), plus a thin black border, which should improve visibility.

**Comment by mauriciopasquier** [comment]
Let me know (and reopen) if these changes are not enough.
